name: Bookshelf
options:
  bundleIdPrefix: com.angad
  deploymentTarget:
    iOS: "12.0"
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "12.0"
    ENABLE_BITCODE: "NO"
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
    SUPPORTS_MACCATALYST: "NO"
targets:
  Bookshelf:
    type: application
    platform: iOS
    sources:
      - Bookshelf
    dependencies:
      - sdk: AVFoundation.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.angad.bookshelf
        PRODUCT_NAME: Bookshelf
        INFOPLIST_FILE: Bookshelf/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
